# site properties and page defaults
title: I+ Lab
subtitle: Intelligent Interaction Lab
description: The ever accelerating process of urbanization enables modern people to live conveniently in a fully-connected world, urging for rich and real-time physiological and psychological healthcare services. To this end, Intelligent Interaction (I+) lab aims to integrate promising tools from diversified fields like Signal Processing (SP), Artificial Intelligence (AI) and Machine Learning (ML) to develop innovative technologies and systems for smart ambient sensing and context understanding with a focus on pervasive computing and affective computing.
header: images/background_5.jpg
footer: images/background_3.png
proofer: false

# site social media and other links
links:
  email: iplus2024@163.com
  # orcid: 0000-0001-8713-9213
  # google-scholar: ETJoidYAAAAJ
  github: I-UESTC
  # twitter: I-UESTC
  # youtube: I-UESTC

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
