- id: 10.1109/ICME57554.2024.10688346
  image: https://csdl-images.ieeecomputer.org/website/default-covers/proceedings/proceedings.jpg

- id:  10.1109/INFOCOM52122.2024.10621430
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: 10.1109/TAFFC.2024.3399328
  image: https://csdl-images.ieeecomputer.org/website/default-covers/trans/ta.jpg

