- id: 10.1109/ICME57554.2024.10688346
  image: images/K-Face Net.gif
  tags:
    - CCF B
    - facial expression recognition
    - class imbalance
    - representation learning

- id: 10.1109/INFOCOM52122.2024.10621430
  image: images/MultiHGR.gif
  tags:
    - CCF A
    - Multi-Task
    - Hand Gesture Recognition
    - Cross-Modality
    - Wrist-Worn Devices

- id: 10.1109/TAFFC.2024.3399328
  image: images/EmoTake.png
  buttons:
    - type: github
      link: yibingweng/EmoTake
  tags:
    - Affect Analysis
    - Decision-making
    - Unobtrusive
    - Dataset
    - AI-human Interaction
  
- id: 10.1145/3639824
  image: images/Adaptive Ofloading.png
  tags:
    - sensor
    - edge
    - inference
    - MAE

- id: 10.1109/TMC.2023.3338954
  image: images/PhyFinAtt.gif
  tags:
    - CCF A
    - WiFi connection
    - MAC forgery attack
    - authentication based on PHY information
    - fingerprint attack

- id: 10.1109/THMS.2023.3264247
  image: images/Wital.png
  tags:
    - Wi-Fi
    - CSI
    - sleep monitoring
    - vital signs
    - wireless sensing

- id: 10.1145/3583780.3614806
  image: images/CGCL.png
  tags:
    - CCF B
    - Social Recommendation
    - Celebrity Effect
    - Graph Neural Network

- id: 10.1109/MCOM.001.2200852
  image: images/Emotion-Aware.png

- id: 10.1109/BIGCOM61073.2023.00016
  image: images/DQN.gif
  tags:
    - CCF C
    - Inter-domain networks
    - Border Gateway Protocols
    - Attack Timing Optimization
    - Deep Q-Network

- id: 10.1109/TAFFC.2023.3285777
  image: images/WiFE.gif
  tags:
    - CCF C
    - Gesture recognition
    - facial expression
    - emotion recognition
    - multimodal
    - channel state information
